<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.3750" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2021-11-12T21:38:55" tests="0" file="cypress/integration/secondTest.spec.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Test log out" timestamp="2021-11-12T21:38:55" tests="1" time="0.3600" failures="1">
    <testcase name="Test log out &quot;before each&quot; hook: login to the app for &quot;verify user can log out successfully&quot;" time="0.0000" classname="&quot;before each&quot; hook: login to the app for &quot;verify user can log out successfully&quot;">
      <failure message="`cy.request()` failed on:

https://api.realworld.io/api/users/login

The response we received from your web server was:

  &gt; 403: Forbidden

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: https://api.realworld.io/api/users/login
Headers: {
  &quot;Connection&quot;: &quot;keep-alive&quot;,
  &quot;user-agent&quot;: &quot;Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/8.7.0 Chrome/93.0.4577.82 Electron/14.1.0 Safari/537.36&quot;,
  &quot;accept&quot;: &quot;*/*&quot;,
  &quot;accept-encoding&quot;: &quot;gzip, deflate&quot;,
  &quot;content-type&quot;: &quot;application/json&quot;,
  &quot;content-length&quot;: 61
}
Body: {&quot;user&quot;:{&quot;email&quot;:&quot;lyalpha2401@gmail.com&quot;,&quot;password&quot;:&quot;12345&quot;}}

-----------------------------------------------------------

The response we got was:

Status: 403 - Forbidden
Headers: {
  &quot;date&quot;: &quot;Fri, 12 Nov 2021 21:38:56 GMT&quot;,
  &quot;content-type&quot;: &quot;application/json; charset=utf-8&quot;,
  &quot;content-length&quot;: &quot;47&quot;,
  &quot;connection&quot;: &quot;keep-alive&quot;,
  &quot;x-powered-by&quot;: &quot;Express&quot;,
  &quot;access-control-allow-origin&quot;: &quot;*&quot;,
  &quot;etag&quot;: &quot;W/\&quot;2f-83PWxEwXkLR3WfVjo3wqB0FwKlU\&quot;&quot;,
  &quot;via&quot;: &quot;1.1 vegur&quot;,
  &quot;cf-cache-status&quot;: &quot;DYNAMIC&quot;,
  &quot;expect-ct&quot;: &quot;max-age=604800, report-uri=\&quot;https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\&quot;&quot;,
  &quot;report-to&quot;: &quot;{\&quot;endpoints\&quot;:[{\&quot;url\&quot;:\&quot;https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=8zGmAi545rrqAzahYIuSzCkcIhWHbG90AxSrbjrepDf8asqHacguavtWCOPYZMXSMqd76S96Zbfl095LZOZZLx%2FGwnbPya3A0uUVeBSgsbAonDB1z8%2FyrL953Q2g%2FfkvYd6ydwlsZq0TNylaS5Tq\&quot;}],\&quot;group\&quot;:\&quot;cf-nel\&quot;,\&quot;max_age\&quot;:604800}&quot;,
  &quot;nel&quot;: &quot;{\&quot;success_fraction\&quot;:0,\&quot;report_to\&quot;:\&quot;cf-nel\&quot;,\&quot;max_age\&quot;:604800}&quot;,
  &quot;server&quot;: &quot;cloudflare&quot;,
  &quot;cf-ray&quot;: &quot;6ad2e8fcfbf528d5-DFW&quot;,
  &quot;alt-svc&quot;: &quot;h3=\&quot;:443\&quot;; ma=86400, h3-29=\&quot;:443\&quot;; ma=86400, h3-28=\&quot;:443\&quot;; ma=86400, h3-27=\&quot;:443\&quot;; ma=86400&quot;
}
Body: {
  &quot;errors&quot;: {
    &quot;email or password&quot;: [
      &quot;is invalid&quot;
    ]
  }
}


https://on.cypress.io/request

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Test log out`" type="CypressError"><![CDATA[CypressError: `cy.request()` failed on:

https://api.realworld.io/api/users/login

The response we received from your web server was:

  > 403: Forbidden

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: https://api.realworld.io/api/users/login
Headers: {
  "Connection": "keep-alive",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/8.7.0 Chrome/93.0.4577.82 Electron/14.1.0 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate",
  "content-type": "application/json",
  "content-length": 61
}
Body: {"user":{"email":"lyalpha2401@gmail.com","password":"12345"}}

-----------------------------------------------------------

The response we got was:

Status: 403 - Forbidden
Headers: {
  "date": "Fri, 12 Nov 2021 21:38:56 GMT",
  "content-type": "application/json; charset=utf-8",
  "content-length": "47",
  "connection": "keep-alive",
  "x-powered-by": "Express",
  "access-control-allow-origin": "*",
  "etag": "W/\"2f-83PWxEwXkLR3WfVjo3wqB0FwKlU\"",
  "via": "1.1 vegur",
  "cf-cache-status": "DYNAMIC",
  "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
  "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=8zGmAi545rrqAzahYIuSzCkcIhWHbG90AxSrbjrepDf8asqHacguavtWCOPYZMXSMqd76S96Zbfl095LZOZZLx%2FGwnbPya3A0uUVeBSgsbAonDB1z8%2FyrL953Q2g%2FfkvYd6ydwlsZq0TNylaS5Tq\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
  "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}",
  "server": "cloudflare",
  "cf-ray": "6ad2e8fcfbf528d5-DFW",
  "alt-svc": "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400, h3-28=\":443\"; ma=86400, h3-27=\":443\"; ma=86400"
}
Body: {
  "errors": {
    "email or password": [
      "is invalid"
    ]
  }
}


https://on.cypress.io/request

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Test log out`
    at http://localhost:4200/__cypress/runner/cypress_runner.js:157339:80
    at tryCatcher (http://localhost:4200/__cypress/runner/cypress_runner.js:13212:23)
    at Promise._settlePromiseFromHandler (http://localhost:4200/__cypress/runner/cypress_runner.js:11147:31)
    at Promise._settlePromise (http://localhost:4200/__cypress/runner/cypress_runner.js:11204:18)
    at Promise._settlePromise0 (http://localhost:4200/__cypress/runner/cypress_runner.js:11249:10)
    at Promise._settlePromises (http://localhost:4200/__cypress/runner/cypress_runner.js:11329:18)
    at _drainQueueStep (http://localhost:4200/__cypress/runner/cypress_runner.js:7919:12)
    at _drainQueue (http://localhost:4200/__cypress/runner/cypress_runner.js:7912:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:4200/__cypress/runner/cypress_runner.js:7928:5)
    at Async.drainQueues (http://localhost:4200/__cypress/runner/cypress_runner.js:7798:14)
From Your Spec Code:
    at Context.eval (http://localhost:4200/__cypress/tests?p=cypress\support\index.js:131:6)]]></failure>
    </testcase>
  </testsuite>
</testsuites>